### PR TITLE
Always return attractors

### PR DESCRIPTION
**Pull request by Datseris**
I am preparing a tutorial on Attractors.jl and I found itr very annoying that `basins_fractions` won't return the attractors if a sampler is given. This is changed here so that attractors are always returned.

Technically this is a brteaking change, but I Am assuming this package doesn't have a user base yet so I'll go ahead with it...

### CODE REVIEW

**Comment by awage** [comment]
This change simplifies some code of mine also.

**Comment by Datseris** [comment]
The problem is, this change is not possible. It is not possible for the clustering method to return the attractors if `ics` is not a state space set but a function. So I have to think this through a bit...

**Comment by awage** [comment]
The problem is for the Featurizing mapper I guess? In this case, you have to change the `extract_attractors` function and dispatch on the mapper type.

**Comment by Datseris** [comment]
I have a solution; i am implementing it now

**Comment by Datseris** [comment]
Okay, the solution was to make the function
```
attractors = extract_attractors(mapper)
```
part of the API and make it work for the featurizing mapper as well, but only when `ics` is a statespaceset. For other mappers it always works.

I'll put this in the examples as well and merge and tag.

**Comment by Datseris** [comment]
Yes, I also though of deepcopying the original sampler into the `AttractorsViaFeaturizing`. This can be done as a PR in the future!

**Pull request merged**
