### PR TITLE
Rename some keywords of `AttractorsViaRecurrences`

### LINKED ISSUE #104: Rename keywords of `AttractorsViaRecurrences`
I believe the names of the keywrods of `AttractorsViaRecurrences` are not the best. The problems I notice are:

1. They use too many abbreviations
2. They are inconsistent: `mx_chk_hit_bas` vs `mx_chk_att`. Why one has hit and the other not?
3. They are mis-named. The keywords don't quantify the "maximum" number of consecutive hits. They quantify the _required_ number of consecutive hits. 
4. They never mention "recurrence" even though that is the central concept.

I propose the following renames:

- `mx_chk_fnd_att -> consecutive_recurrences`
- `mx_chk_loc_att -> attractor_locate_steps`
- `mx_chk_att -> consecutive_attractor_steps`
- `mx_chk_hit_bas -> consecutive_basin_steps`
- `mx_chk_lost -> consecutive_lost_steps`
- `mx_chk_safety -> maximum_iterations`

If we agree with these, once we are done with PR #103 , I will open a new PR that does the rename and add deprecations in place.

### PR DESCRIPTION
**Pull request by Datseris**
Closes  #104

This PR does the renaming of #104 and adds changelog entries.

### CODE REVIEW

**Comment by Datseris** [comment]
Yeah this system diverges to infinity:
```
julia> trajectory(ds, 100, [2.0])[1]
1-dimensional StateSpaceSet{Float64} with 101 points
       2.0
      -4.0
      56.0
 -175504.0
       5.405813486073056e15
      -1.5797311146339633e47
       3.942298606396109e141
     -Inf
     -Inf
     -Inf
       ⋮
     -Inf
     -Inf
     -Inf
     -Inf
     -Inf
     -Inf
     -Inf
     -Inf
     -Inf
```
Which makes sense of course, as x^3 is larger than x when x > 1...............

**Comment by awage** [comment]
I have no problem with the keywords changes. But  is there a string doc in the code where we say that these keywords are equivalent to the old ones? It can be also a legacy `basins_of_attraction` function.

**Comment by Datseris** [comment]
No, this is said in the CHANGELOG. Why would be in a docstring? The docstrings are only meaningful for the current version of the code. They have no reason to refer to prior versions.

**Comment by Datseris** [comment]
@awage is it okay that this change is mentioned in the changelog?

**Comment by awage** [comment]
Ok, I understand. So it is deprecated but the keywords are still accepted until the next breaking release? In the changelog it should be clear that the keywords are still accepted until the next breaking version. Then we can forget about them.

**Comment by Datseris** [comment]
This is what "deprecated" means. Quite literally: "the names are still accepted until the next breaking release. They will be removed at the next breaking release. They are not mentioned anywhere in the documentation."

**Comment by theogf** [comment]
I might be wrong but it looks like the old kwargs are not accepted anymore?

**Comment by Datseris** [comment]
There should be. If not, it's a bug. Do you have a MWE? If yes, open an new issue!

**Pull request merged**
